apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-id
  namespace: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-id
  template:
    metadata:
      labels:
        app: generate-id
    spec:
      containers:
        - name: generate-id-code
          image: sepidmas/reuse_scale-generate-id-code:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          volumeMounts:
            - name: argo-shard
              mountPath: /mnt/data/argo-shard
              subPath: generate-id
      volumes:
        - name: argo-shard
          persistentVolumeClaim:
            claimName: argo-shard-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: generate-id
  namespace: pipeline
spec:
  selector:
    app: generate-id
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP