---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtaskresults"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-sa-binding
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: pipeline
roleRef:
  kind: ClusterRole
  name: argo-workflow
  apiGroup: rbac.authorization.k8s.io
