apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-sa-binding
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: pipeline
roleRef:
  kind: ClusterRole
  name: argo-cluster-role
  apiGroup: rbac.authorization.k8s.io
