apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: generate-birthday
  namespace: pipeline
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - name: generate-birthday
          image: sepidmas/reuse_scale-generate-birthday:knative
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: argo-shard
              mountPath: /mnt/data/argo-shard
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: argo-shard
          persistentVolumeClaim:
            claimName: argo-shard-pvc
