apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-shard-pvc
  namespace: no-reuse-pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: zfs
