apiVersion: v1
kind: Pod
metadata:
  name: pvc-copy
  namespace: no-reuse-pipeline
spec:
  containers:
  - name: pvc-copy
    image: busybox
    command: ["sh", "-c", "sleep 3600"]   # ensure container stays running
    volumeMounts:
    - name: data
      mountPath: /mnt/data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: argo-shard-pvc
  restartPolicy: Never
