apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: no-reuse-pipeline
spec:
  containers:
  - name: inspector
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /mnt/data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: argo-shard-pvc
  restartPolicy: Never